articles = [
    "le", "la", "les", "l'",
    "un", "une", "des", "d'", "du",
    "au", "aux", "avec", 'de', 'à'
    "ce", "cet", "cette", "ces",
    "mon", "ton", "son", "ma", "ta", "sa", "mes", "tes", "ses",
    "notre", "votre", "leur", "nos", "vos", "leurs",
    "quel", "quelle", "quels", "quelles",
    "aucun", "aucune", "aucuns", "aucunes",
    "maint", "mainte", "maints", "maintes",
    "que",
    "tel", "telle" , "tels", "telles",
    "tout", "toute", "tous", "toutes",
    "chaque",
    "plusieurs", "divers",
    "autre", "autres", "même", "mêmes ", "quelque", "quelques",
    "quelconque", "quelconques",
    "certain", "certaine ", "certains", "certaines",
    "divers", "diverse ", "divers", "diverses",
    "différent", "différente ", "différents", "différentes",
    "nul", "nulle", "nuls", "nulles",
]
